//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaOdev.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int BiletID { get; set; }
        public int FilmID { get; set; }
        public Nullable<System.DateTime> BiletTarih { get; set; }
        public string BiletKoltukNumara { get; set; }
        public Nullable<int> SatisID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Satis Satis { get; set; }
    }
}
