//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaOdev.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinemaOtomasyonuEntities : DbContext
    {
        public SinemaOtomasyonuEntities()
            : base("name=SinemaOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<Calisan> Calisan { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<FilmTur> FilmTur { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<Satis> Satis { get; set; }
        public virtual DbSet<Seans> Seans { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
